import type { ClientSolicitationCardData } from './client-solicitation-card.types';

export const MOCK_CLIENT_SOLICITATIONS: ClientSolicitationCardData[] = [
  {
    id: 'sol-1',
    status: 'emergencia',
    title: 'Pensão Alimentícia',
    description: 'Meu ex não paga a pensão do meu filho há meses e preciso de ajuda urgente.',
    date: '25/06/2026',
    lawyerCount: 4,
    footerVariant: 'accepted',
  },
  {
    id: 'sol-2',
    status: 'urgente',
    title: 'Pensão Alimentícia',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do.',
    date: '25/06/2026',
    lawyerCount: 12,
    footerVariant: 'compatible',
  },
  {
    id: 'sol-3',
    status: 'medio',
    title: 'Divórcio Consensual',
    description: 'Preciso de orientação para iniciar um processo de divórcio amigável.',
    date: '18/06/2026',
    lawyerCount: 7,
    footerVariant: 'compatible',
  },
  {
    id: 'sol-4',
    status: 'urgente',
    title: 'Inventário',
    description: 'Família em disputa sobre partilha de bens após falecimento.',
    date: '10/06/2026',
    lawyerCount: 2,
    footerVariant: 'accepted',
  },
  {
    id: 'sol-5',
    status: 'emergencia',
    title: 'Medida Protetiva',
    description: 'Situação de risco e necessidade de orientação jurídica imediata.',
    date: '02/06/2026',
    lawyerCount: 9,
    footerVariant: 'compatible',
  },
  {
    id: 'sol-6',
    status: 'tenho_tempo',
    title: 'Consultoria Contratual',
    description: 'Quero revisar um contrato de prestação de serviços sem urgência.',
    date: '28/05/2026',
    lawyerCount: 3,
    footerVariant: 'compatible',
  },
];
